blank_issues_enabled: true
contact_links:
  - name: Quiquitocoin Core Security Policy
    url: https://github.com/quiquitocoin/quiquitocoin/blob/master/SECURITY.md
    about: View security policy
  - name: Quiquitocoin Core Developers
    url: https://quiquitocoincore.org
    about: Quiquitocoin Core homepage
